name: Matrix and Uses workflow
on:
  push:
    branches: ["main"]
jobs:
  tools-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout le code
        uses: actions/checkout@v4
      - name: Installer NODEJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Installer python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Afficher les versions
        run: |
          echo "Node version est :"
          node --version
          echo "Python version est :"
          python --version
