name: Matrix and Uses workflow
on:
  workflow_dispatch:
jobs:
  tools-test:
    runs-on: ubuntu-latest
    steps:
      - name: Installer NODEJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Installer python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Afficher les versions
        run: |
          echo "Node version est :"
          node --version
          "echo Python version est :"
          python --version
