name: Create files and zip files
on:
  push:
    branches: ["main"]
jobs:
  job-A:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create 3 files
        run: |
              touch .github/workflows/log1.txt
              touch .github/workflows/log2.txt
              touch .github/workflows/log3.txt
      - name: Upload files as artifact
        uses: actions/upload-artifact@v4
        with:   
          name: uploaded-file1
          path: .github/workflows/*
  job-B:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: uploaded-file1
      - name: create zip file
        run:
          zip archive_logs.zip *.txt
      - name: show content of zip file
        run:
          unzip -l archive_logs.zip
