name: Create files and zip files
on:
  push:
    branches: ["main"]
jobs:
  job-A:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create 3 files
        run: |
              touch log1.txt
              touch log2.txt
              touch log3.txt
      - name: Upload files as artifact
        uses: actions/upload-artifact@v4
        with:   
          name: uploaded-logs
          path: |
                log1.txt
                log2.txt
                log3.txt
  job-B:
    needs: job-A
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: uploaded-logs
      - name: create zip file
        run: |
          zip archive_logs.zip *.txt
      - name: show content of zip file
        run: |
          unzip -l archive_logs.zip
