name: Env and Secrets demo
on: 
  push:
    branches: ["main"]

env:
  APP_NAME: "Mon Application"  # Variable globale

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:  
      - name: Afficher la variable globale
        run: echo "La variable globale est App_Name = $APP_NAME"
  
      - name: Utiliser un secret
        run: echo "La clé API secrète est = ${{secrets.API_KEY}}"
